# Generated by Django 4.1 on 2022-08-20 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('OrganizationName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OrganizationID', models.IntegerField()),
                ('OrganizationLocation', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RouteWiseData',
            fields=[
                ('RouteID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Mean', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationSurrogateKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StationID', models.IntegerField()),
                ('Division', models.CharField(max_length=16)),
                ('StationType', models.CharField(choices=[('B', 'BMDStation'), ('O', 'OrganizationStation')], max_length=1)),
                ('BMDLocation', models.CharField(max_length=20)),
                ('OrganizationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StationAirQuality',
            fields=[
                ('AQID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('PM25', models.FloatField()),
                ('AverageTemp', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('RainPrecipitation', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('WindSpeed', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Visibility', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('CloudCover', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('RelativeHumidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=6)),
                ('Date', models.DateField()),
                ('StationSurrogateKey', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.station')),
            ],
        ),
    ]
